export const GENERATED_HEADER =
  "# Generated by pnpm run env — do not edit by hand. Edit root .env.local instead.\n";

export const DEPLOY_GENERATED_HEADER = [
  "# =============================================================================",
  "# Bondery stack — copy to .env and fill secrets",
  "# Generated by pnpm run env — do not edit by hand. Edit packages/helpers/src/env/manifest.ts.",
  "# docker compose -f deploy/bondery/docker-compose.yml --env-file deploy/bondery/.env up -d",
  "# =============================================================================",
].join("\n");

export const OPS_GENERATED_HEADER = [
  "# =============================================================================",
  "# Bondery ops (marketing website) — copy to .env for Dokploy / local smoke",
  "# Generated by pnpm run env — do not edit by hand. Edit packages/helpers/src/env/manifest.ts.",
  "# docker compose -f deploy/ops/docker-compose.yml --env-file deploy/ops/.env up -d",
  "#",
  "# Omit BONDERY_INFRA_WEBSITE_IMAGE_TAG to pull the floating :production channel.",
  "# =============================================================================",
].join("\n");

export const PLAUSIBLE_GENERATED_HEADER = [
  "# =============================================================================",
  "# Plausible Community Edition — Dokploy env UI or compose .env",
  "# Generated by pnpm run env — do not edit by hand. Edit packages/helpers/src/env/manifest.ts.",
  "# docker compose -f deploy/plausible/compose.yml --env-file deploy/plausible/.env up -d",
  "# =============================================================================",
].join("\n");

export function quoteEnvValue(value: string) {
  if (/[\s#"'$\\]/.test(value) || value === "") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

/** Stable ASCII sort for generated env files (must match across OS/locale). */
export function compareAscii(a: string, b: string) {
  return a.localeCompare(b, "en", { sensitivity: "variant" });
}

export function sortEnvRows<T extends { group: string; key: string }>(rows: T[]) {
  return rows.toSorted((a, b) => {
    if (a.group !== b.group) {
      return compareAscii(a.group, b.group);
    }
    return compareAscii(a.key, b.key);
  });
}

export function formatEnvFile(
  vars: Array<{
    commented?: boolean;
    description?: string;
    group: string;
    key: string;
    value: string;
  }>,
  options?: {
    commented?: boolean;
    footer?: string;
    groupGuides?: Readonly<Record<string, readonly string[]>>;
    header?: string;
    includeDescriptions?: boolean;
  },
) {
  const lines = [(options?.header ?? GENERATED_HEADER).trimEnd()];
  let lastGroup = "";
  for (const row of vars) {
    if (row.group !== lastGroup) {
      lines.push("");
      lines.push(`# --- ${row.group} ---`);
      const guide = options?.groupGuides?.[row.group];
      if (guide) {
        for (const guideLine of guide) {
          lines.push(guideLine === "" ? "#" : `# ${guideLine}`);
        }
      }
      lastGroup = row.group;
    }
    if (row.description && options?.includeDescriptions !== false) {
      for (const descriptionLine of row.description.split("\n")) {
        lines.push(`# ${descriptionLine}`);
      }
    }
    const assignment = `${row.key}=${quoteEnvValue(row.value)}`;
    lines.push(row.commented ? `# ${assignment}` : assignment);
  }
  if (options?.footer) {
    lines.push("");
    lines.push(options.footer);
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}
