import {
  ALICE_ID,
  CREATED_AT,
  GROUP_ID,
  INTERACTION_ID,
  PERSON_ID,
  RELATIONSHIP_ID,
  TAG_ID,
} from "./me-import-constants.js";

export function aliceFixture() {
  return {
    groupMemberships: [
      {
        createdAt: CREATED_AT,
        groupId: GROUP_ID,
        id: "gm-ada",
        personId: PERSON_ID,
        userId: ALICE_ID,
      },
      {
        createdAt: CREATED_AT,
        groupId: GROUP_ID,
        id: "gm-alice",
        personId: ALICE_ID,
        userId: ALICE_ID,
      },
    ],
    groups: [
      {
        color: "#aabbcc",
        createdAt: CREATED_AT,
        emoji: "👋",
        id: GROUP_ID,
        label: "Friends",
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
    ],
    interactions: [
      {
        createdAt: CREATED_AT,
        date: CREATED_AT,
        description: "Coffee",
        id: INTERACTION_ID,
        participants: [{ personId: PERSON_ID }, { personId: ALICE_ID }],
        title: "Catch-up",
        type: "Coffee",
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
    ],
    people: [
      {
        addresses: [
          {
            addressCity: "Prague",
            addressCountry: "Czechia",
            addressCountryCode: "CZ",
            addressFormatted: "Main 1, Prague",
            addressGeocodeSource: "mapy.com",
            addressGranularity: "address",
            addressLine1: "Main 1",
            addressLine2: null,
            addressPostalCode: "11000",
            addressState: null,
            addressStateCode: null,
            createdAt: CREATED_AT,
            geocodeConfidence: "high",
            id: "addr-1",
            label: "Home",
            latitude: 50.1,
            longitude: 14.4,
            personId: PERSON_ID,
            sortOrder: 0,
            timezone: "Europe/Prague",
            type: "home",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
            value: "Main 1, Prague",
          },
        ],
        createdAt: CREATED_AT,
        emails: [
          {
            createdAt: CREATED_AT,
            id: "email-1",
            personId: PERSON_ID,
            preferred: true,
            sortOrder: 0,
            type: "personal",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
            value: "ada@example.com",
          },
        ],
        firstName: "Ada",
        hasAvatar: true,
        headline: "Engineer",
        id: PERSON_ID,
        importantDates: [
          {
            createdAt: CREATED_AT,
            date: CREATED_AT,
            id: "date-1",
            note: null,
            notifyDaysBefore: 3,
            notifyOn: CREATED_AT,
            personId: PERSON_ID,
            type: "birthday",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
          },
        ],
        keepFrequencyDays: 30,
        language: "en",
        lastInteraction: CREATED_AT,
        lastInteractionActivityId: INTERACTION_ID,
        lastName: "Lovelace",
        latitude: 50.1,
        linkedin: {
          bio: "Builder",
          educationHistory: [
            {
              createdAt: CREATED_AT,
              degree: "BA",
              description: null,
              endDate: null,
              id: "edu-1",
              schoolLinkedinId: null,
              schoolName: "University",
              startDate: CREATED_AT,
              updatedAt: CREATED_AT,
              userId: ALICE_ID,
            },
          ],
          workHistory: [
            {
              companyLinkedinId: null,
              companyName: "Acme",
              createdAt: CREATED_AT,
              description: null,
              employmentType: "full-time",
              endDate: null,
              id: "work-1",
              location: "Prague",
              startDate: CREATED_AT,
              title: "Engineer",
              updatedAt: CREATED_AT,
              userId: ALICE_ID,
            },
          ],
        },
        location: "Prague",
        longitude: 14.4,
        middleName: null,
        myself: false,
        notes: "Met at a meetup",
        notesUpdatedAt: CREATED_AT,
        phones: [
          {
            createdAt: CREATED_AT,
            id: "phone-1",
            personId: PERSON_ID,
            preferred: true,
            prefix: "+420",
            sortOrder: 0,
            type: "mobile",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
            value: "123456789",
          },
        ],
        socials: [
          {
            connectedAt: CREATED_AT,
            createdAt: CREATED_AT,
            handle: "ada",
            id: "social-1",
            personId: PERSON_ID,
            platform: "linkedin",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
          },
        ],
        timezone: "Europe/Prague",
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
      {
        addresses: [],
        createdAt: CREATED_AT,
        emails: [
          {
            createdAt: CREATED_AT,
            id: "alice-email-1",
            personId: ALICE_ID,
            preferred: true,
            sortOrder: 0,
            type: "personal",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
            value: "alice@example.com",
          },
        ],
        firstName: "Alice",
        hasAvatar: true,
        headline: null,
        id: ALICE_ID,
        importantDates: [],
        keepFrequencyDays: null,
        language: "en",
        lastInteraction: null,
        lastInteractionActivityId: null,
        lastName: "Owner",
        latitude: null,
        linkedin: null,
        location: null,
        longitude: null,
        middleName: null,
        myself: true,
        notes: "Should not overwrite Bob",
        notesUpdatedAt: null,
        phones: [
          {
            createdAt: CREATED_AT,
            id: "alice-phone-1",
            personId: ALICE_ID,
            preferred: true,
            prefix: "+420",
            sortOrder: 0,
            type: "mobile",
            updatedAt: CREATED_AT,
            userId: ALICE_ID,
            value: "999",
          },
        ],
        socials: [],
        timezone: null,
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
    ],
    relationships: [
      {
        createdAt: CREATED_AT,
        id: RELATIONSHIP_ID,
        relationshipType: "friend",
        sourcePersonId: PERSON_ID,
        targetPersonId: ALICE_ID,
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
    ],
    tagMemberships: [
      {
        createdAt: CREATED_AT,
        id: "tm-1",
        personId: PERSON_ID,
        tagId: TAG_ID,
        userId: ALICE_ID,
      },
    ],
    tags: [
      {
        color: "#112233",
        createdAt: CREATED_AT,
        id: TAG_ID,
        label: "VIP",
        updatedAt: CREATED_AT,
        userId: ALICE_ID,
      },
    ],
  };
}
