/**
 * Canonical environment variable contract for the Bondery monorepo.
 *
 * Humans edit root `.env.local` using these canonical names.
 * `npm run env` copies identity (or documented aliases) into per-app files.
 *
 * Naming:
 * - BONDERY_PUBLIC_*  — safe for clients
 * - BONDERY_PRIVATE_* — secrets (API / auth setup)
 * - BONDERY_INFRA_*   — deploy / runtime plumbing
 * - BONDERY_DEV_*     — local API dev boot only (never set in Compose/production)
 * - BONDERY_OPS_*     — CI only (never synced into app local files)
 */

export type EnvEnvironment = "development" | "production";

export type TargetId = "api" | "webapp" | "website" | "mobile" | "chrome-extension" | "db";

export type EnvTargetWrite = {
  /** App / package id */
  id: TargetId;
  /**
   * Name written into the target file.
   * Defaults to the canonical name when omitted (identity).
   */
  runtimeName?: string;
  /**
   * When set, derive the value from another canonical key (e.g. callback URL).
   * If `transform` is omitted, copies the source value as-is under `runtimeName`.
   */
  deriveFrom?: string;
  /** Optional value transform when deriving */
  transform?: "webapp-auth-callback";
};

export type EnvVarDef = {
  canonical: string;
  description: string;
  /** Include in generated root `.env.local.example` */
  exampleValue: string;
  /** Group header in generated files */
  group: string;
  requiredIn: EnvEnvironment[];
  secret: boolean;
  targets: EnvTargetWrite[];
  /** When false, omit from turbo cache env arrays (rare) */
  turboAffectsCache?: boolean;
};

export type SyncTargetConfig = {
  id: TargetId;
  /** Relative to repo root */
  devFile: string;
  /** Relative to repo root — committed example regenerated by `npm run env -- --write-examples` */
  exampleFile: string;
  /** Optional alternate example for production shape */
  productionExampleFile?: string;
};

/** Where `npm run env` writes per-app local files */
export const SYNC_TARGETS: SyncTargetConfig[] = [
  {
    devFile: "apps/api/.env.development.local",
    exampleFile: "apps/api/.env.development.example",
    id: "api",
    productionExampleFile: "apps/api/.env.production.example",
  },
  {
    devFile: "apps/webapp/.env.development.local",
    exampleFile: "apps/webapp/.env.development.example",
    id: "webapp",
    productionExampleFile: "apps/webapp/.env.production.example",
  },
  {
    devFile: "apps/website/.env.development.local",
    exampleFile: "apps/website/.env.development.local.example",
    id: "website",
    productionExampleFile: "apps/website/.env.production.local.example",
  },
  {
    devFile: "apps/mobile/.env.local",
    exampleFile: "apps/mobile/.env.example",
    id: "mobile",
  },
  {
    devFile: "apps/chrome-extension/.env.development.local",
    exampleFile: "apps/chrome-extension/.env.development.example",
    id: "chrome-extension",
    productionExampleFile: "apps/chrome-extension/.env.production.example",
  },
  {
    devFile: "packages/db/.env.local",
    exampleFile: "packages/db/.env.local.example",
    id: "db",
  },
];

function t(id: TargetId, runtimeName?: string): EnvTargetWrite {
  return runtimeName ? { id, runtimeName } : { id };
}

export const ENV_MANIFEST: EnvVarDef[] = [
  // --- Public URLs ---
  {
    canonical: "BONDERY_PUBLIC_API_URL",
    description: "Public API base URL (no trailing /api)",
    exampleValue: "http://localhost:26631",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("chrome-extension"), t("mobile")],
  },
  {
    canonical: "BONDERY_PUBLIC_WEBAPP_URL",
    description: "Public webapp origin",
    exampleValue: "http://localhost:26632",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("website"), t("chrome-extension"), t("mobile")],
  },
  {
    canonical: "BONDERY_PUBLIC_WEBSITE_URL",
    description: "Public marketing website origin",
    exampleValue: "http://localhost:26630",
    group: "Public URLs",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp"), t("website"), t("mobile")],
  },
  {
    canonical: "BONDERY_PUBLIC_EXTRA_ALLOWED_ORIGINS",
    description: "Comma-separated extra CORS origins (e.g. Expo web)",
    exampleValue: "http://localhost:26634",
    group: "Public URLs",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },

  // --- Database ---
  {
    canonical: "DATABASE_URL",
    description: "Postgres connection string (Prisma + API)",
    exampleValue: "postgresql://postgres:password@127.0.0.1:54322/bondery",
    group: "Database",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api"), t("db")],
  },

  // --- Auth (Better Auth) ---
  {
    canonical: "BONDERY_PRIVATE_BETTER_AUTH_SECRETS",
    description:
      "Better Auth versioned secrets (format: version:secret[,version:secret...]; highest version first)",
    exampleValue: "1:your-super-secret-better-auth-secret-min-32-chars",
    group: "Auth",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_AUTH_GITHUB_CLIENT_ID",
    description: "GitHub OAuth client id for Better Auth",
    exampleValue: "",
    group: "Auth",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_AUTH_GITHUB_CLIENT_SECRET",
    description: "GitHub OAuth client secret for Better Auth",
    exampleValue: "",
    group: "Auth",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_AUTH_LINKEDIN_CLIENT_ID",
    description: "LinkedIn OAuth client id for Better Auth",
    exampleValue: "",
    group: "Auth",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_AUTH_LINKEDIN_CLIENT_SECRET",
    description: "LinkedIn OAuth client secret for Better Auth",
    exampleValue: "",
    group: "Auth",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_OAUTH_CLIENT_ID",
    description:
      "Chrome extension OAuth client id (synced as legacy name below). Also consumed by the API's deployment-time OAuth client provisioning.",
    exampleValue: "",
    group: "Auth",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("chrome-extension")],
  },
  {
    canonical: "BONDERY_PUBLIC_WEBAPP_OAUTH_CLIENT_ID",
    description:
      "Webapp's own OAuth client id (confidential BFF client of the API's oauth-provider)",
    exampleValue: "",
    group: "Auth",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_WEBAPP_OAUTH_CLIENT_SECRET",
    description:
      "Webapp's own OAuth client secret (never exposed to the browser). The API only ever stores/verifies its hash via deployment-time provisioning; it never round-trips the plaintext value.",
    exampleValue: "",
    group: "Auth",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api"), t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_WEBAPP_SESSION_SECRET",
    description: "Symmetric key (≥32 chars) for encrypting the webapp's own session cookie",
    exampleValue: "your-super-secret-webapp-session-secret-min-32-chars",
    group: "Auth",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("webapp")],
  },

  // --- Storage ---
  {
    canonical: "BONDERY_PUBLIC_STORAGE_URL",
    description: "Public base URL for SeaweedFS S3 objects (no trailing slash).",
    exampleValue: "https://storage.usebondery.com",
    group: "Storage",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api"), t("mobile")],
  },
  {
    canonical: "BONDERY_PRIVATE_S3_ENDPOINT",
    description: "Internal SeaweedFS S3 gateway URL (API container).",
    exampleValue: "http://seaweedfs-s3:8333",
    group: "Storage",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_S3_REGION",
    description: "S3 region accepted by SeaweedFS (any value).",
    exampleValue: "eu-central-1",
    group: "Storage",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_S3_ACCESS_KEY_ID",
    description: "SeaweedFS S3 access key id (API client + rendered into seaweedfs-s3 at startup).",
    exampleValue: "bondery_access_key",
    group: "Storage",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_S3_SECRET_ACCESS_KEY",
    description:
      "SeaweedFS S3 secret access key (API client + rendered into seaweedfs-s3 at startup).",
    exampleValue: "",
    group: "Storage",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_INFRA_STORAGE_DOMAIN",
    description: "Public hostname for SeaweedFS S3 (Traefik Host rule in compose).",
    exampleValue: "storage.usebondery.com",
    group: "Storage",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },

  // --- API secrets ---
  {
    canonical: "BONDERY_PRIVATE_SERVICE_SECRET",
    description: "Internal service-to-service HMAC secret",
    exampleValue: "<your-service-secret>",
    group: "API secrets",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_PLATFORM_ADMIN_EMAILS",
    description:
      "Comma-separated operator emails promoted to user.role=admin by provision-platform-admins at deploy",
    exampleValue: "ops@example.com",
    group: "API secrets",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_PLATFORM_ADMIN_USER_IDS",
    description:
      "Optional break-glass comma-separated user UUIDs with platform admin access (Better Auth adminUserIds)",
    exampleValue: "",
    group: "API secrets",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_HOST",
    description: "SMTP host",
    exampleValue: "smtp.example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_PORT",
    description: "SMTP port",
    exampleValue: "587",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_USER",
    description: "SMTP username",
    exampleValue: "robot@example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_PASS",
    description: "SMTP password",
    exampleValue: "your-email-password",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_EMAIL_ADDRESS",
    description: "From address for transactional email",
    exampleValue: "robot@example.com",
    group: "Email",
    requiredIn: ["development", "production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_REDIS_URL",
    description: "Redis connection URL",
    exampleValue: "redis://127.0.0.1:26636",
    group: "Redis",
    requiredIn: ["development", "production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_STRIPE_SECRET_KEY",
    description: "Stripe API secret key",
    exampleValue: "sk_test_<your-stripe-secret-key>",
    group: "Stripe",
    requiredIn: ["production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_STRIPE_WEBHOOK_SECRET",
    description: "Stripe webhook signing secret",
    exampleValue: "whsec_<your-stripe-webhook-secret>",
    group: "Stripe",
    requiredIn: ["production"],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_BILLING_UPGRADES_ENABLED",
    description: "Enable in-app subscription upgrades (true | false)",
    exampleValue: "false",
    group: "Stripe",
    requiredIn: [],
    secret: false,
    targets: [t("api"), t("webapp")],
  },
  {
    canonical: "BONDERY_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    description: "Stripe publishable key for embedded Checkout",
    exampleValue: "pk_test_<your-stripe-publishable-key>",
    group: "Stripe",
    requiredIn: ["production"],
    secret: false,
    targets: [t("api"), t("webapp")],
  },
  {
    canonical: "BONDERY_PUBLIC_STRIPE_PRICE_ID_MONTHLY",
    description: "Stripe Price ID for monthly Premium",
    exampleValue: "price_<monthly>",
    group: "Stripe",
    requiredIn: ["production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_STRIPE_PRICE_ID_ANNUAL",
    description: "Stripe Price ID for annual Premium",
    exampleValue: "price_<annual>",
    group: "Stripe",
    requiredIn: ["production"],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PUBLIC_MAPS_URL",
    description: "Mapy.com API base URL",
    exampleValue: "https://api.mapy.com",
    group: "Maps",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_MAPS_KEY",
    description: "Mapy.com API key",
    exampleValue: "<your-maps-api-key>",
    group: "Maps",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_ANTHROPIC_API_KEY",
    description: "Anthropic API key for AI features",
    exampleValue: "sk-ant-<your-anthropic-api-key>",
    group: "AI",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },

  // --- Analytics ---
  {
    canonical: "BONDERY_PUBLIC_POSTHOG_KEY",
    description: "PostHog project API key (browser)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PUBLIC_POSTHOG_HOST",
    description: "PostHog host URL",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_KEY",
    description: "PostHog personal/project key for server-side capture (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_HOST",
    description: "PostHog host for server-side capture (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_API_SECRET",
    description: "PostHog personal API key for admin analytics queries (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: true,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTHOG_PROJECT_ID",
    description: "PostHog project id for admin analytics queries (optional)",
    exampleValue: "",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "DO_NOT_TRACK",
    description: "Disable analytics / vendor telemetry when true",
    exampleValue: "true",
    group: "Analytics",
    requiredIn: [],
    secret: false,
    targets: [t("api"), t("webapp"), t("website")],
  },

  // --- Infra (optional local) ---
  {
    canonical: "BONDERY_INFRA_VERSION",
    description: "App version surfaced in webapp runtime config",
    exampleValue: "",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_INFRA_GIT_SHA",
    description: "Git SHA surfaced in webapp runtime config",
    exampleValue: "",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("webapp")],
  },
  {
    canonical: "BONDERY_INFRA_CHROME_EXTENSION_ID",
    description:
      "Chrome Web Store extension ID. Used to derive the https://{id}.chromiumapp.org/ redirect URI registered for the extension's OAuth client (see scripts/provision-oauth-clients.ts).",
    exampleValue: "lpcmokfekjjejnpobhbkgmjkodfhpmha",
    group: "Infra",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
  },
  {
    canonical: "BONDERY_PRIVATE_POSTGRES_PASSWORD",
    description: "Postgres password for bundled self-hosted database",
    exampleValue: "your-super-secret-and-long-postgres-password",
    group: "Database",
    requiredIn: [],
    secret: true,
    targets: [t("db")],
  },
  {
    canonical: "BONDERY_PUBLIC_SYNC_DEBUG",
    description: "Mobile sync debug logging (1/true)",
    exampleValue: "",
    group: "Mobile",
    requiredIn: [],
    secret: false,
    targets: [t("mobile")],
  },

  // --- Local dev (API boot only; not used in Compose pre_start) ---
  {
    canonical: "BONDERY_DEV_SKIP_RELEASE_MIGRATE",
    description:
      "When true, skip release-migrate (prisma deploy + functions.sql + OAuth + platform admins) on API dev boot",
    exampleValue: "",
    group: "Local dev (API)",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
    turboAffectsCache: false,
  },
  {
    canonical: "BONDERY_DEV_SKIP_STORAGE_BUCKETS",
    description: "When true, skip SeaweedFS bucket ensure on API dev boot",
    exampleValue: "",
    group: "Local dev (API)",
    requiredIn: [],
    secret: false,
    targets: [t("api")],
    turboAffectsCache: false,
  },
];

/** System / pass-through vars always listed in turbo globalPassThroughEnv */
export const TURBO_SYSTEM_PASSTHROUGH = [
  "PATH",
  "WINDIR",
  "HOME",
  "USERPROFILE",
  "TMP",
  "TEMP",
  "TMPDIR",
  "NODE_ENV",
  "CI",
  "GITHUB_ACTIONS",
  "TURBO_TELEMETRY_DISABLED",
  "TURBO_TEAM",
  "TURBO_TOKEN",
  "npm_package_version",
  "METRO_MAX_WORKERS",
  "PORT",
  "LOG_LEVEL",
  "SYNC_WAKE_ENABLED",
  "NEXT_RUNTIME",
  "DO_NOT_TRACK",
  "NO_COLOR",
  "FORCE_COLOR",
] as const;

/** Ops secrets — GitHub Actions only; never written by `npm run env` */
export const OPS_ENV_VARS = [
  "BONDERY_OPS_CHROME_EXTENSION_ID",
  "BONDERY_OPS_CHROME_PUBLISHER_ID",
  "PRIVATE_CHROME_SERVICE_ACCOUNT_KEY_JSON",
  "PRIVATE_CHROME_PRIVATE_SIGNING_KEY",
  "BONDERY_OPS_DISCORD_WEBHOOK_URL",
  "BONDERY_OPS_GHCR_WRITE_TOKEN",
  "BONDERY_OPS_REDDIT_CLIENT_ID",
  "BONDERY_OPS_REDDIT_CLIENT_SECRET",
  "BONDERY_OPS_REDDIT_PASSWORD",
  "BONDERY_OPS_REDDIT_USERNAME",
  "BONDERY_OPS_TURBO_TEAM",
  "BONDERY_OPS_TURBO_TOKEN",
] as const;

export function applyTransform(transform: EnvTargetWrite["transform"], value: string): string {
  const base = value.replace(/\/$/, "");
  if (transform === "webapp-auth-callback") {
    return `${base}/auth/callback`;
  }
  return value;
}

export function getRequiredVarsForTarget(
  targetId: TargetId,
  environment: EnvEnvironment,
): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    if (!entry.requiredIn.includes(environment)) {
      continue;
    }
    for (const target of entry.targets) {
      if (target.id !== targetId) {
        continue;
      }
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  return [...names].sort();
}

export function getRuntimeNamesForTarget(targetId: TargetId): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    if (entry.turboAffectsCache === false) {
      continue;
    }
    for (const target of entry.targets) {
      if (target.id !== targetId) {
        continue;
      }
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  return [...names].sort();
}

export function getAllRuntimeNames(): string[] {
  const names = new Set<string>();
  for (const entry of ENV_MANIFEST) {
    names.add(entry.canonical);
    for (const target of entry.targets) {
      names.add(target.runtimeName ?? entry.canonical);
    }
  }
  for (const name of OPS_ENV_VARS) {
    names.add(name);
  }
  return [...names].sort();
}

export function resolveCanonicalValue(
  rootEnv: Record<string, string>,
  entry: EnvVarDef,
  target: EnvTargetWrite,
): string | undefined {
  if (target.deriveFrom) {
    const source = rootEnv[target.deriveFrom];
    if (source === undefined || source === "") {
      return undefined;
    }
    return applyTransform(target.transform, source);
  }
  const value = rootEnv[entry.canonical];
  if (value === undefined) {
    return undefined;
  }
  return value;
}
