export interface Contact {
  id: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  title?: string;
  place?: string;
  description: string;
  notes?: string;
  avatarColor: string;
  avatar?: string;
  lastInteraction: Date;
  createdAt?: Date;
  connections?: string[];
  phone?: string;
  email?: string;
  linkedin?: string;
  instagram?: string;
  whatsapp?: string;
  facebook?: string;
  website?: string;
  signal?: string;
  birthdate?: Date;
  notifyBirthday?: boolean;
  importantDates?: Array<{
    date: Date;
    name: string;
    notify: boolean;
  }>;
  myself?: boolean;
  position?: {
    lat: number;
    lng: number;
  };
}

export const mockContacts: Contact[] = [
  {
    id: "0",
    firstName: "John",
    lastName: "Doe",
    description: "That's you!",
    avatarColor: "violet",
    lastInteraction: new Date(),
    myself: true,
    connections: [],
  },
  {
    id: "1",
    firstName: "Alice",
    middleName: "Marie",
    lastName: "Johnson",
    title: "Software Engineer",
    place: "San Francisco, CA",
    description: "Close friend from college",
    notes:
      "<p>Met at freshman orientation. <strong>Great debugging partner!</strong></p><ul><li>Loves hiking</li><li>Coffee enthusiast</li><li>Planning to visit Portland next month</li></ul>",
    avatarColor: "blue",
    avatar: "https://i.pravatar.cc/150?img=1",
    lastInteraction: new Date("2025-12-20"),
    connections: ["0", "2", "5", "8"],
    phone: "+1234567890",
    email: "alice@example.com",
    linkedin: "alice",
    instagram: "alice",
    whatsapp: "+1234567890",
    website: "https://alicejohnson.dev",
    signal: "+1234567890",
    birthdate: new Date("1992-03-15"),
    notifyBirthday: true,
    importantDates: [
      {
        date: new Date("2020-06-15"),
        name: "First day at current job",
        notify: true,
      },
      {
        date: new Date("2015-09-01"),
        name: "College graduation",
        notify: false,
      },
    ],
    position: { lat: 37.7749, lng: -122.4194 },
  },
  {
    id: "2",
    firstName: "Bob",
    lastName: "Smith",
    title: "Product Manager",
    place: "New York, NY",
    description: "Work colleague",
    notes:
      '<p>Worked together on Q3 project launch.</p><blockquote><p>"Always ship on time" - his motto</p></blockquote><p><strong>Skills:</strong> Product strategy, user research</p>',
    avatarColor: "green",
    avatar: "https://i.pravatar.cc/150?img=12",
    lastInteraction: new Date("2025-12-25"),
    connections: ["0", "1", "4", "7"],
    phone: "+9876543210",
    email: "bob@example.com",
    linkedin: "bob",
    facebook: "bob",
    birthdate: new Date("1988-07-22"),
    notifyBirthday: false,
    importantDates: [
      {
        date: new Date("2010-08-20"),
        name: "Wedding anniversary",
        notify: true,
      },
    ],
    position: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: "3",
    firstName: "Carol",
    middleName: "Anne",
    lastName: "Williams",
    title: "Graphic Designer",
    place: "Los Angeles, CA",
    description: "Neighbor",
    avatarColor: "pink",
    avatar: "https://i.pravatar.cc/150?img=5",
    lastInteraction: new Date("2025-12-15"),
    connections: ["0", "6"],
    email: "carol@example.com",
    instagram: "carol",
    whatsapp: "+9876543210",
    position: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Brown",
    title: "Personal Trainer",
    place: "Austin, TX",
    description: "Gym buddy",
    notes:
      "<p><strong>Training Schedule:</strong> Mon/Wed/Fri 6am</p><p>Focusing on strength training this quarter.</p><p><em>Remember:</em> He's vegetarian - good restaurant recommendations needed!</p>",
    avatarColor: "orange",
    avatar: "https://i.pravatar.cc/150?img=13",
    lastInteraction: new Date("2025-12-22"),
    connections: ["0", "2", "7"],
    phone: "+5551234567",
    whatsapp: "+5551234567",
    facebook: "david",
    signal: "+5551234567",
    birthdate: new Date("1995-11-08"),
    notifyBirthday: true,
    position: { lat: 30.2672, lng: -97.7431 },
  },
  {
    id: "5",
    firstName: "Emma",
    middleName: "Rose",
    lastName: "Davis",
    title: "Author & Writer",
    place: "Seattle, WA",
    description: "Book club member",
    notes:
      '<h1>Latest Novel</h1><p>Working on a mystery thriller set in Pacific Northwest.</p><p><strong>Publication date:</strong> Spring 2026</p><ul><li>Ask her about writing process</li><li>Recommended "The Silent Patient"</li></ul>',
    avatarColor: "violet",
    avatar: "https://i.pravatar.cc/150?img=9",
    lastInteraction: new Date("2025-12-18"),
    connections: ["0", "1", "6", "8"],
    phone: "+1122334455",
    email: "emma@example.com",
    linkedin: "emma",
    instagram: "emma",
    website: "https://emmadavisauthor.com",
    birthdate: new Date("1990-05-20"),
    notifyBirthday: true,
    importantDates: [
      {
        date: new Date("2018-03-12"),
        name: "First book published",
        notify: true,
      },
      {
        date: new Date("2022-11-08"),
        name: "Won literary award",
        notify: false,
      },
      {
        date: new Date("2019-07-04"),
        name: "Moved to Seattle",
        notify: false,
      },
    ],
    position: { lat: 47.6062, lng: -122.3321 },
  },
  {
    id: "6",
    firstName: "Frank",
    lastName: "Miller",
    place: "Boston, MA",
    description: "Childhood friend",
    avatarColor: "cyan",
    avatar: "https://i.pravatar.cc/150?img=15",
    lastInteraction: new Date("2025-11-30"),
    connections: ["0", "3", "5"],
    email: "frank@example.com",
    position: { lat: 42.3601, lng: -71.0589 },
  },
  {
    id: "7",
    firstName: "Grace",
    lastName: "Wilson",
    title: "Certified Yoga Instructor",
    place: "Denver, CO",
    description: "Yoga instructor",
    avatarColor: "teal",
    avatar: "https://i.pravatar.cc/150?img=20",
    lastInteraction: new Date("2025-12-24"),
    connections: ["0", "2", "4"],
    phone: "+9998887776",
    instagram: "grace",
    facebook: "grace",
    birthdate: new Date("1993-09-12"),
    notifyBirthday: false,
    position: { lat: 39.7392, lng: -104.9903 },
  },
  {
    id: "8",
    firstName: "Henry",
    middleName: "James",
    lastName: "Moore",
    title: "Data Analyst",
    place: "Chicago, IL",
    description: "Former roommate",
    avatarColor: "red",
    avatar: "https://i.pravatar.cc/150?img=33",
    lastInteraction: new Date("2025-12-10"),
    connections: ["0", "1", "5"],
    phone: "+6667778889",
    email: "henry@example.com",
    linkedin: "henry",
    position: { lat: 41.8781, lng: -87.6298 },
  },
  {
    id: "9",
    firstName: "Iris",
    lastName: "Taylor",
    title: "UX Designer",
    place: "Portland, OR",
    description: "Met at design conference",
    avatarColor: "blue",
    avatar: "https://i.pravatar.cc/150?img=25",
    lastInteraction: new Date("2025-12-19"),
    connections: ["0", "3", "12", "15"],
    email: "iris@example.com",
    linkedin: "iris",
    birthdate: new Date("1994-01-30"),
    notifyBirthday: true,
    position: { lat: 45.5152, lng: -122.6784 },
  },
  {
    id: "10",
    firstName: "Jack",
    middleName: "Alexander",
    lastName: "Anderson",
    title: "Marketing Director",
    place: "Miami, FL",
    description: "Business partner",
    notes:
      "<h2>Marketing Campaign Q1</h2><ul><li>Budget approved: $50K</li><li>Launch date: Feb 15</li><li>Focus on social media growth</li></ul><p><strong>Next meeting:</strong> January 5th</p>",
    avatarColor: "green",
    avatar: "https://i.pravatar.cc/150?img=60",
    lastInteraction: new Date("2025-12-23"),
    connections: ["0", "2", "11", "20"],
    phone: "+3334445555",
    email: "jack@example.com",
    linkedin: "jack",
    website: "https://jackanderson.marketing",
    birthdate: new Date("1987-12-05"),
    notifyBirthday: true,
    position: { lat: 25.7617, lng: -80.1918 },
  },
  {
    id: "11",
    firstName: "Kate",
    lastName: "Thomas",
    title: "Sales Manager",
    place: "Houston, TX",
    description: "Former colleague",
    avatarColor: "pink",
    lastInteraction: new Date("2025-12-16"),
    connections: ["0", "10", "14"],
    phone: "+7778889999",
    email: "kate@example.com",
    position: { lat: 29.7604, lng: -95.3698 },
  },
  {
    id: "12",
    firstName: "Liam",
    lastName: "Jackson",
    title: "Frontend Developer",
    place: "San Jose, CA",
    description: "Coding bootcamp friend",
    avatarColor: "orange",
    avatar: "https://i.pravatar.cc/150?img=52",
    lastInteraction: new Date("2025-12-21"),
    connections: ["0", "1", "9", "18"],
    email: "liam@example.com",
    linkedin: "liam",
    instagram: "liam",
    birthdate: new Date("1996-06-18"),
    notifyBirthday: false,
    position: { lat: 37.3382, lng: -121.8863 },
  },
  {
    id: "13",
    firstName: "Mia",
    middleName: "Grace",
    lastName: "White",
    title: "Content Creator",
    place: "Nashville, TN",
    description: "Social media influencer",
    avatarColor: "violet",
    avatar: "https://i.pravatar.cc/150?img=32",
    lastInteraction: new Date("2025-12-14"),
    connections: ["0", "16", "22"],
    instagram: "mia",
    whatsapp: "+1231231234",
    position: { lat: 36.1627, lng: -86.7816 },
  },
  {
    id: "14",
    firstName: "Noah",
    lastName: "Harris",
    title: "Financial Analyst",
    place: "Charlotte, NC",
    description: "University friend",
    avatarColor: "cyan",
    lastInteraction: new Date("2025-12-11"),
    connections: ["0", "11", "19"],
    phone: "+4445556666",
    email: "noah@example.com",
    position: { lat: 35.2271, lng: -80.8431 },
  },
  {
    id: "15",
    firstName: "Olivia",
    lastName: "Martin",
    title: "HR Manager",
    place: "Phoenix, AZ",
    description: "Professional contact",
    avatarColor: "teal",
    avatar: "https://i.pravatar.cc/150?img=47",
    lastInteraction: new Date("2025-12-17"),
    connections: ["0", "9", "21"],
    email: "olivia@example.com",
    linkedin: "olivia",
    birthdate: new Date("1991-10-25"),
    notifyBirthday: true,
    position: { lat: 33.4484, lng: -112.074 },
  },
  {
    id: "16",
    firstName: "Paul",
    lastName: "Garcia",
    title: "Photographer",
    place: "San Diego, CA",
    description: "Creative collaborator",
    avatarColor: "red",
    lastInteraction: new Date("2025-12-13"),
    connections: ["0", "13", "25"],
    instagram: "paul",
    position: { lat: 32.7157, lng: -117.1611 },
  },
  {
    id: "17",
    firstName: "Quinn",
    lastName: "Martinez",
    title: "Chef",
    place: "New Orleans, LA",
    description: "Culinary school friend",
    avatarColor: "blue",
    lastInteraction: new Date("2025-12-09"),
    connections: ["0", "23", "28"],
    phone: "+5556667777",
    position: { lat: 29.9511, lng: -90.0715 },
  },
  {
    id: "18",
    firstName: "Rachel",
    middleName: "Elizabeth",
    lastName: "Robinson",
    title: "Backend Developer",
    place: "Raleigh, NC",
    description: "Tech meetup contact",
    avatarColor: "green",
    avatar: "https://i.pravatar.cc/150?img=44",
    lastInteraction: new Date("2025-12-22"),
    connections: ["0", "1", "12", "24"],
    email: "rachel@example.com",
    linkedin: "rachel",
    birthdate: new Date("1997-02-14"),
    notifyBirthday: true,
    position: { lat: 35.7796, lng: -78.6382 },
  },
  {
    id: "19",
    firstName: "Sam",
    lastName: "Clark",
    title: "Investment Banker",
    place: "Boston, MA",
    description: "Finance network",
    avatarColor: "pink",
    lastInteraction: new Date("2025-12-08"),
    connections: ["0", "14", "26"],
    phone: "+8889990000",
    email: "sam@example.com",
    position: { lat: 42.3601, lng: -71.0589 },
  },
  {
    id: "20",
    firstName: "Tara",
    lastName: "Rodriguez",
    title: "Brand Strategist",
    place: "Atlanta, GA",
    description: "Marketing colleague",
    avatarColor: "orange",
    avatar: "https://i.pravatar.cc/150?img=38",
    lastInteraction: new Date("2025-12-20"),
    connections: ["0", "10", "27"],
    email: "tara@example.com",
    linkedin: "tara",
    birthdate: new Date("1989-04-07"),
    notifyBirthday: false,
    position: { lat: 33.749, lng: -84.388 },
  },
  {
    id: "21",
    firstName: "Uma",
    lastName: "Lewis",
    title: "Recruiter",
    place: "Dallas, TX",
    description: "Job search contact",
    avatarColor: "violet",
    lastInteraction: new Date("2025-12-12"),
    connections: ["0", "15", "29"],
    phone: "+1112223333",
    email: "uma@example.com",
    position: { lat: 32.7767, lng: -96.797 },
  },
  {
    id: "22",
    firstName: "Victor",
    lastName: "Lee",
    title: "Video Editor",
    place: "Las Vegas, NV",
    description: "Media production",
    avatarColor: "cyan",
    lastInteraction: new Date("2025-12-18"),
    connections: ["0", "13", "30"],
    instagram: "victor",
    position: { lat: 36.1699, lng: -115.1398 },
  },
  {
    id: "23",
    firstName: "Wendy",
    lastName: "Walker",
    title: "Pastry Chef",
    place: "San Antonio, TX",
    description: "Culinary arts",
    avatarColor: "teal",
    lastInteraction: new Date("2025-12-07"),
    connections: ["0", "17", "31"],
    phone: "+2223334444",
    position: { lat: 29.4241, lng: -98.4936 },
  },
  {
    id: "24",
    firstName: "Xander",
    lastName: "Hall",
    title: "DevOps Engineer",
    place: "Philadelphia, PA",
    description: "Tech conference",
    avatarColor: "red",
    lastInteraction: new Date("2025-12-21"),
    connections: ["0", "18", "32"],
    email: "xander@example.com",
    linkedin: "xander",
    position: { lat: 39.9526, lng: -75.1652 },
  },
  {
    id: "25",
    firstName: "Yara",
    lastName: "Allen",
    title: "Fashion Designer",
    place: "Miami, FL",
    description: "Art community",
    avatarColor: "blue",
    lastInteraction: new Date("2025-12-15"),
    connections: ["0", "16", "33"],
    instagram: "yara",
    position: { lat: 25.7617, lng: -80.1918 },
  },
  {
    id: "26",
    firstName: "Zack",
    lastName: "Young",
    title: "Hedge Fund Manager",
    place: "New York, NY",
    description: "Investment circle",
    avatarColor: "green",
    lastInteraction: new Date("2025-12-06"),
    connections: ["0", "19", "34"],
    phone: "+3334445556",
    email: "zack@example.com",
    position: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: "27",
    firstName: "Ava",
    lastName: "King",
    title: "Social Media Manager",
    place: "Tampa, FL",
    description: "Digital marketing",
    avatarColor: "pink",
    lastInteraction: new Date("2025-12-19"),
    connections: ["0", "20", "35"],
    email: "ava@example.com",
    instagram: "ava",
    position: { lat: 27.9506, lng: -82.4572 },
  },
  {
    id: "28",
    firstName: "Ben",
    lastName: "Wright",
    title: "Sommelier",
    place: "Napa, CA",
    description: "Wine enthusiast",
    avatarColor: "orange",
    lastInteraction: new Date("2025-12-05"),
    connections: ["0", "17", "36"],
    phone: "+4445556667",
    position: { lat: 38.2975, lng: -122.2869 },
  },
  {
    id: "29",
    firstName: "Chloe",
    lastName: "Lopez",
    title: "Talent Acquisition",
    place: "Indianapolis, IN",
    description: "HR network",
    avatarColor: "violet",
    lastInteraction: new Date("2025-12-10"),
    connections: ["0", "21", "37"],
    email: "chloe@example.com",
    linkedin: "chloe",
    position: { lat: 39.7684, lng: -86.1581 },
  },
  {
    id: "30",
    firstName: "Dylan",
    lastName: "Hill",
    title: "Film Director",
    place: "Los Angeles, CA",
    description: "Film industry",
    avatarColor: "cyan",
    lastInteraction: new Date("2025-12-16"),
    connections: ["0", "22", "38"],
    instagram: "dylan",
    position: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: "31",
    firstName: "Ella",
    lastName: "Scott",
    title: "Cake Artist",
    place: "Charleston, SC",
    description: "Baking workshop",
    avatarColor: "teal",
    lastInteraction: new Date("2025-12-04"),
    connections: ["0", "23"],
    phone: "+5556667778",
    position: { lat: 32.7765, lng: -79.9311 },
  },
  {
    id: "32",
    firstName: "Finn",
    lastName: "Green",
    title: "Cloud Architect",
    place: "Seattle, WA",
    description: "AWS meetup",
    avatarColor: "red",
    lastInteraction: new Date("2025-12-20"),
    connections: ["0", "24", "1"],
    email: "finn@example.com",
    linkedin: "finn",
    position: { lat: 47.6062, lng: -122.3321 },
  },
  {
    id: "33",
    firstName: "Gina",
    lastName: "Adams",
    title: "Stylist",
    place: "Nashville, TN",
    description: "Fashion industry",
    avatarColor: "blue",
    lastInteraction: new Date("2025-12-14"),
    connections: ["0", "25"],
    instagram: "gina",
    position: { lat: 36.1627, lng: -86.7816 },
  },
  {
    id: "34",
    firstName: "Hugo",
    lastName: "Baker",
    title: "Portfolio Manager",
    place: "Chicago, IL",
    description: "Finance sector",
    avatarColor: "green",
    lastInteraction: new Date("2025-12-03"),
    connections: ["0", "26", "8"],
    phone: "+6667778889",
    email: "hugo@example.com",
    position: { lat: 41.8781, lng: -87.6298 },
  },
  {
    id: "35",
    firstName: "Ivy",
    lastName: "Gonzalez",
    title: "Community Manager",
    place: "Orlando, FL",
    description: "Social media",
    avatarColor: "pink",
    lastInteraction: new Date("2025-12-17"),
    connections: ["0", "27"],
    email: "ivy@example.com",
    whatsapp: "+7778889990",
    position: { lat: 28.5383, lng: -81.3792 },
  },
  {
    id: "36",
    firstName: "Jake",
    lastName: "Nelson",
    title: "Wine Specialist",
    place: "Sonoma, CA",
    description: "Vineyard tour",
    avatarColor: "orange",
    lastInteraction: new Date("2025-12-02"),
    connections: ["0", "28"],
    phone: "+8889990001",
    position: { lat: 38.2919, lng: -122.458 },
  },
  {
    id: "37",
    firstName: "Kara",
    lastName: "Carter",
    title: "Senior Recruiter",
    place: "Columbus, OH",
    description: "Job fair",
    avatarColor: "violet",
    lastInteraction: new Date("2025-12-09"),
    connections: ["0", "29"],
    email: "kara@example.com",
    linkedin: "kara",
    position: { lat: 39.9612, lng: -82.9988 },
  },
  {
    id: "38",
    firstName: "Leo",
    lastName: "Mitchell",
    title: "Cinematographer",
    place: "Austin, TX",
    description: "Film festival",
    avatarColor: "cyan",
    lastInteraction: new Date("2025-12-15"),
    connections: ["0", "30", "4"],
    instagram: "leo",
    position: { lat: 30.2672, lng: -97.7431 },
  },
];
